# Generated by Django 2.1.5 on 2019-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCreds',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
